version: '3'

x-volumes:
    &default-volumes
    volumes:
        - $PWD/files:/files

x-environment:
    &default-environment
    environment:
        - DISPLAY=host.docker.internal:0
        - USER=root

##################################################
# """Services"""
##################################################

services:
  #Generation of Feynman diagrams and cross-section calculation
  madgraph_mg:
    << : *default-environment
    << : *default-volumes
    image: scailfin/madgraph5-amc-nlo
      
  whizard:
    << : *default-environment
    << : *default-volumes
    image: whizard/whizard-weekly:master
  
  # whizard2:
  #   << : *default-environment
  #   << : *default-volumes
  #   image: whizard
  #   volumes:
  #     - $PWD/files:/files

  pythia:
    << : *default-environment
    << : *default-volumes
    image: matthewfeickert/pythia-python

  #Delphes simulation
  delphes:
    << : *default-environment
    << : *default-volumes
    image: valentem1992/delphes:3.5.0
    # command: 
    #   ./DelphesHepMC card.tcl files/output.root test.hepmc